# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Canvas' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Canvas

pod 'Alamofire', '~> 5.2'
pod 'IQKeyboardManagerSwift', '6.3.0'
pod 'GoogleMaps', '3.9.0'
pod 'GooglePlaces', '3.9.0'
pod 'Charts'
pod 'SwiftyGif'
pod 'MaterialShowcase'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'Firebase/Messaging'
pod 'Kingfisher', '~> 7.0'
pod 'IOSSecuritySuite'




  target 'CanvasTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CanvasUITests' do
    # Pods for testing
  end

end
